export const countrys = [
    { country: "Afeganistão",},
    { country: "África do Sul",},
    { country: "Albânia",},
    { country: "Alemanha",},
    { country: "Andorra",},
    { country: "Angola",},
    { country: "Anguilla",},
    { country: "Antártica",},
    { country: "Antígua e Barbuda",},
    { country: "Arábia Saudita",},
    { country: "Argélia",},
    { country: "Argentina",},
    { country: "Armênia",},
    { country: "Aruba",},
    { country: "Austrália",},
    { country: "Áustria",},
    { country: "Azerbaijão",},
    { country: "Bahamas",},
    { country: "Bangladesh",},
    { country: "Barbados",},
    { country: "Barém",},
    { country: "Belarus",},
    { country: "Bélgica",},
    { country: "Belize",},
    { country: "Benin",},
    { country: "Bermuda",},
    { country: "Birmânia",},
    { country: "Bolívia",},
    { country: "Bósnia e Herzegovina",},
    { country: "Botswana",},
    { country: "Brasil",},
    { country: "Brunei",},
    { country: "Bulgária",},
    { country: "Burkina Faso",},
    { country: "Burundi",},
    { country: "Butão",},
    { country: "Cabo Verde",},
    { country: "Camarões",},
    { country: "Camboja",},
    { country: "Canadá",},
    { country: "Cazaquistão",},
    { country: "Chad",},
    { country: "Chile",},
    { country: "China",},
    { country: "Chipre",},
    { country: "Cingapura",},
    { country: "Cisjordânia / Faixa de Gaza",},
    { country: "Colômbia",},
    { country: "Cômoros",},
    { country: "Congo, República Democrática do",},
    { country: "Congo, República do",},
    { country: "Coreia do Norte",},
    { country: "Coreia do Sul",},
    { country: "Costa do Marfim",},
    { country: "Costa Rica",},
    { country: "Croácia",},
    { country: "Cuba",},
    { country: "Curaçao",},
    { country: "Dinamarca",},
    { country: "Djibuti",},
    { country: "Dominica",},
    { country: "Egito",},
    { country: "El Salvador",},
    { country: "Emirados Árabes Unidos",},
    { country: "Equador",},
    { country: "Eritréia",},
    { country: "Eslováquia",},
    { country: "Eslovênia",},
    { country: "Espanha",},
    { country: "Estados Unidos",},
    { country: "Estônia",},
    { country: "Etiópia",},
    { country: "Fiji",},
    { country: "Filipinas",},
    { country: "Finlândia",},
    { country: "França",},
    { country: "França Metropolitana",},
    { country: "Gabão",},
    { country: "Gâmbia",},
    { country: "Gana",},
    { country: "Geórgia",},
    { country: "Geórgia do Sul e Ilhas",},
    { country: "Gibraltar",},
    { country: "Grécia",},
    { country: "Greenland",},
    { country: "Grenada",},
    { country: "Guadelupe",},
    { country: "Guam",},
    { country: "Guatemala",},
    { country: "Guernsey",},
    { country: "Guiana",},
    { country: "Guiana Francesa",},
    { country: "Guiné",},
    { country: "Guiné Equatorial",},
    { country: "Guiné-Bissau",},
    { country: "Haiti",},
    { country: "Holanda",},
    { country: "Honduras",},
    { country: "Hong Kong",},
    { country: "Hungria",},
    { country: "Iêmen",},
    { country: "Ilha Bouvet",},
    { country: "Ilha Christmas",},
    { country: "Ilha de Man",},
    { country: "Ilha Norfolk",},
    { country: "Ilhas Caiman",},
    { country: "Ilhas Cocos (Keeling)",},
    { country: "Ilhas Cook",},
    { country: "Ilhas Falkland (Malvinas)",},
    { country: "Ilhas Feroe",},
    { country: "Ilhas Heard and McDonald",},
    { country: "Ilhas Marianas do Norte",},
    { country: "Ilhas Marshall",},
    { country: "Ilhas Maurício",},
    { country: "Ilhas Menores Distantes dos Estados Unidos",},
    { country: "Ilhas Pitcairn",},
    { country: "Ilhas Salomão",},
    { country: "Ilhas Turks e Caicos",},
    { country: "Ilhas Virgens Americanas",},
    { country: "Ilhas Virgens Britânicas",},
    { country: "Ilhas Wallis e Futuna",},
    { country: "Índia",},
    { country: "Indonésia",},
    { country: "Irã",},
    { country: "Iraque",},
    { country: "Irlanda",},
    { country: "Islândia",},
    { country: "Israel",},
    { country: "Itália",},
    { country: "Jamaica",},
    { country: "Japão",},
    { country: "Jersey",},
    { country: "Jordânia",},
    { country: "Kiribati",},
    { country: "Kosovo",},
    { country: "Kuwait",},
    { country: "Laos",},
    { country: "Lesoto",},
    { country: "Letônia",},
    { country: "Líbano",},
    { country: "Libéria",},
    { country: "Líbia",},
    { country: "Liechtenstein",},
    { country: "Lituânia",},
    { country: "Luxemburgo",},
    { country: "Macao",},
    { country: "Macedônia",},
    { country: "Madagascar",},
    { country: "Maiote",},
    { country: "Malásia",},
    { country: "Malawi",},
    { country: "Maldivas",},
    { country: "Mali",},
    { country: "Malta",},
    { country: "Marrocos",},
    { country: "Martinica",},
    { country: "Mauritânia",},
    { country: "México",},
    { country: "Micronésia, Estados Federados da",},
    { country: "Moçambique",},
    { country: "Moldova",},
    { country: "Mônaco",},
    { country: "Mongólia",},
    { country: "Montenegro",},
    { country: "Montserrat",},
    { country: "Namíbia",},
    { country: "NÃO INFORMADO",},
    { country: "Nauru",},
    { country: "Nepal",},
    { country: "Nicarágua",},
    { country: "Níger",},
    { country: "Nigéria",},
    { country: "Niue",},
    { country: "Noruega",},
    { country: "Nova Caledônia",},
    { country: "Nova Zelândia",},
    { country: "Omã",},
    { country: "Palau",},
    { country: "Panamá",},
    { country: "Papua Nova Guiné",},
    { country: "Paquistão",},
    { country: "Paraguai",},
    { country: "Peru",},
    { country: "Polinésia Francesa",},
    { country: "Polônia",},
    { country: "Porto Rico",},
    { country: "Portugal",},
    { country: "Qatar",},
    { country: "Quênia",},
    { country: "Quirguistão",},
    { country: "Reino Unido",},
    { country: "República Centro-Africana",},
    { country: "República Dominicana",},
    { country: "República Tcheca",},
    { country: "Reunião",},
    { country: "Romênia",},
    { country: "Ruanda",},
    { country: "Rússia",},
    { country: "Saara Ocidental",},
    { country: "Saint Martin",},
    { country: "Saint Pierre e Miquelon",},
    { country: "Samoa",},
    { country: "Samoa Americana",},
    { country: "San Marino",},
    { country: "Santa Helena, Ascensão e Tristão da Cunha",},
    { country: "Santa Lúcia",},
    { country: "Santa Sé (Cidade do Vaticano)",},
    { country: "São Bartolomeu",},
    { country: "São Cristóvão e Nevis",},
    { country: "São Martinho",},
    { country: "São Tomé e Príncipe",},
    { country: "São Vicente e Granadinas",},
    { country: "Seicheles",},
    { country: "Senegal",},
    { country: "Serra Leoa",},
    { country: "Sérvia",},
    { country: "Síria",},
    { country: "Somália",},
    { country: "Sri Lanka",},
    { country: "Suazilândia",},
    { country: "Sudão",},
    { country: "Sudão do Sul",},
    { country: "Suécia",},
    { country: "Suíça",},
    { country: "Sul da França e Antártica",},
    { country: "Suriname",},
    { country: "Svalbard",},
    { country: "Tadjiquistão",},
    { country: "Tailândia",},
    { country: "Taiwan",},
    { country: "Tanzânia",},
    { country: "Território Britânico do Oceano Índico",},
    { country: "Timor-Leste",},
    { country: "Togo",},
    { country: "Tonga",},
    { country: "Toquelau",},
    { country: "Trinidad e Tobago",},
    { country: "Tunísia",},
    { country: "Turcomenistão",},
    { country: "Turquia",},
    { country: "Tuvalu",},
    { country: "Ucrânia",},
    { country: "Uganda",},
    { country: "Uruguai",},
    { country: "Uzbequistão",},
    { country: "Vanuatu",},
    { country: "Venezuela",},
    { country: "Vietnã",},
    { country: "Zâmbia",},
    { country: "Zimbáb",}
];

export default countrys;