const orgaoExp =[
    {orgao:"SSP (CART IDENT)",},
    {orgao:"CNH (CAR.NAC.HABIL)",},
    {orgao:"CN (CERT.NASCTO)",},
    {orgao:"CT (CART.TRABALHO",},
    {orgao:"C.CONS (CART.CONSU",},
    {orgao:"CBOMB (COR.BOMBEIRO)",},
    {orgao:"CE (CART. ESTRAN)",},
    {orgao:"CIM (C.ID.MAGISTR.)",},
    {orgao:"CNTR (C.N.T.RADIOLOG",},
    {orgao:"COREC (CON.REG.ECON)",},
    {orgao:"COREN (CONS.REG.ENF)",},
    {orgao:"CRA (CONS.REG.ADM.)",},
    {orgao:"CRAS (C.R.ASSIS.SOC)",},
    {orgao:"CRB (C.R. BIOLOGIA)",},
    {orgao:"CRBM (C.REG.BIOMED.)",},
    {orgao:"CRC (CON.REG.CONT.)",},
    {orgao:"CREA (CONS.REG.ENG)",},
    {orgao:"CRECI (C.R.CORR.IMOV",},
    {orgao:"CREF (CR.EDU.FISICA)",},
    {orgao:"CREP (C.R.ECON.PROF)",},
    {orgao:"CRF (CON.REG.FARM)",},
    {orgao:"CRFA (CON.REG.FONOAU",},
    {orgao:"CRFTO (C.R.FISI.TER.)",},
    {orgao:"CRM (CONS.REG.MED.)",},
    {orgao:"CRMV (C.R.MED.VETERI)",},
    {orgao:"CRN (C.REG.NUTRIC.)",},
    {orgao:"CRO (CON.REG.ODONT)",},
    {orgao:"CRP (C.R.PSICOL.)",},
    {orgao:"CRPRL (PROF.REL.PUB)' ",},
    {orgao:"CRQ (CON.REG.QUIM)",},
    {orgao:"DETRAN (CART IDENT)' =",},
    {orgao:"IFP (INS.FELIX PAC)",},
    {orgao:"IPF (INS.PEREI.FA)",},
    {orgao:"MA (MIN.AGRICULTURA",},
    {orgao:"MAER (MINIST.AERON.)",},
    {orgao:"MDEFESA (MIN.DEFESA)",},
    {orgao:"ME (MINIST.EXERC.",},
    {orgao:"MEC (MINIST.EDUCACAO",},
    {orgao:"MF (MIN. FAZENDA",},
    {orgao:"MM (MINIST.MARIN.",},
    {orgao:"MRE (MIN.REL.EXTERN)",},
    {orgao:"MT (MIN.TRANSPORTE",},
    {orgao:"OAB (ORD ADV BRAS)",},
    {orgao:"OMB (ORDEM MUS.BR)",},
    {orgao:"PASS (PASSAPORTE)",},
    {orgao:"PMCE (POL.MILI.CEARA)",},
    {orgao:"PMEPE (POL.MILITARPE)",},
    {orgao:"PMERJ (POL.MILITARRJ)",},
    {orgao:"PMES (POL.MILITARES)",},
    {orgao:"PMESP (POL.MILITARSP)",},
    {orgao:"PMGO (POL.MILI.GOIAS')",},
    {orgao:"PMMG (POL.MILITARMG)",},
    {orgao:"SJESP (SIND.JORN.SP)",},
    {orgao:"TCE (TRIB.CON.ESTAD)",},
    {orgao:"TJ (TRIB.JUSTICA",},
    {orgao:"TRE (TRIB.REG.ELEIT)",},
    {orgao:"TRF (TRIB.REG.FEDER)",},
    {orgao:"TRT (TRIB.REG.TRAB",},
]
export default orgaoExp